### ISSUE TITLE
[バグ？] アップデートでインストール済みのAviutlが消える 

### ISSUE THREAD

**Issue by nusu-github** [minfia/AviUtlAutoInstaller#6]
問題の内容

AviUtlAutoInstaller v1.3.0 から AviUtlAutoInstaller v1.4.0 に「アプリのアップデート」を使ってアップデートを行うとインストール済みのAviutlフォルダーが消えてしまい勝手に削除される

実行環境

Windows 10 21H2 19044.1415 日本語環境

再現手順

- v1.3.0をダウンロードして任意の場所に展開
- 「アプリのアップデート」を行わずにインストールを行う
- AviUtlAutoInstallerを閉じ、再度開く
- 「アプリのアップデート」を行う
- アップデートが完了するとAviutlフォルダーが消えている

修正すべき内容

削除しないようにする。若しくは実行する前に通知する。出来れば更新する毎にAviutlのバックアップを行う。
また、削除は完全削除ではなくゴミ箱に送る方式にすることで万が一に対応できると考えられる。

**Comment by minfia** [comment]
ありがとうございます。
こちらでも再現することを確認いたしました。
* 環境
    Windows 10 20H2 19042.1348

発生条件は、aai.exe, updater.exeと同じ場所にAviUtlフォルダが存在している場合に削除されるようです。
以下の2パターンでAviUtlをインストールし、確認を行いました。
* パターン1
   AviUtlのインストール先をaai.exe, updater.exeのある場所に行う
* パターン2
   AviUtlのインストール先をデスクトップに行う

アップデートはupdater.exe内で削除、削除の除外を行っています。
原因ですが、除外する項目に"AviUtl"フォルダが存在しないため、アップデート時に削除してしまいます。

対応としては、”削除しないようにする"となるかと思われます。
バグとして挙げさせていただきます。

**Comment by minfia** [comment]
以下のコミットにて修正しました。
削除除外対象の指定をaai.exe側に持たせるようにしたので、修正というより変更に近いですが……。
f74c1635e4817458c1ce2d4bffadc7dfe43d81e4

#7, #8 についてご対応いただきありがとうございます。
改めましてお礼申し上げます。
